### ISSUE TITLE
no documentation

### ISSUE THREAD

**Issue by natostanco** [rivir99/multiplyX#1]
can you pls add some documentation? code is not commented at all

**Comment by rivir99** [comment]
fuck you, pay me

**Comment by rivir99** [comment]
strobe light means RAVE PARTY

**Comment by natostanco** [comment]
I understand drugs are nice but pls keep them out of github :)

**Comment by rivir99** [comment]
i added noob-notes.
if you cant read python, idk how you are supposed to read english though...
